class Supplemental {
  static SUPPLEMENTAL = [
    {
      first: ['punctuation', 'mortar words', 'remove'],
      second: [
        ['punctuation', '.', ',', '?', '!', '—', '…'],
        [
          'mortar words',
          'a',
          'am',
          'an',
          'and',
          'are',
          'as',
          'at',
          'but',
          'by',
          'for',
          'in',
          'is',
          'of',
          'on',
          'or',
          'so',
          'than',
          'that',
          'the',
          'to',
          'was',
          'were',
          'yet',
        ],
      ],
    },
  ];
}

class WordLists_Solved {
  static SOLVED_0 = [
    {
      top: 'who',
      first: [
        'who',
        'someone',
        'presence',
        'human',
        'subjectively',
        'exist',
        'be',
      ],
      second: [
        ['someone', 'somebody'],
        ['human', 'humans', 'humanly'],
        ['subjectively', 'subjective'],
        ['exist', 'existence', 'exists', 'existed', 'existing'],
        ['be', 'being', 'beings', 'been'],
      ],
    },
    {
      top: 'walks',
      first: [
        'step',
        'gait',
        'wanderer',
        'roaming',
        'meanderingly',
        'ramble',
        'walks',
      ],
      second: [
        ['step', 'steps', 'stepped', 'stepping'],
        ['wanderer', 'wanderers', 'wander', 'wanders', 'wandered', 'wandering'],
        ['roaming', 'roam', 'roams', 'roamed'],
        ['meanderingly', 'meander', 'meanders', 'meandered', 'meandering'],
        ['ramble', 'rambles', 'rambled', 'rambling'],
        ['walks', 'walk', 'walked', 'walking'],
      ],
    },
    {
      supplemental: 'the',
      first: null,
      second: null,
    },
    {
      top: 'changing',
      first: [
        'tide',
        'current',
        'changable',
        'mercurially',
        'vascilate',
        'oscilate',
      ],
      second: [
        ['tide', 'tides'],
        ['current', 'currents'],
        ['changable', 'change', 'changes', 'changed', 'changing'],
        ['mercurially', 'mercurial'],
        ['vascilate', 'vascilates', 'vascilated', 'vascilating'],
        ['oscilate', 'oscilates', 'oscilated', 'oscilating'],
      ],
    },
    {
      top: 'path',
      first: ['how', 'way', 'path', 'pliant', 'biddably', 'trace', 'follow'],
      second: [
        ['way', 'ways'],
        ['path', 'paths'],
        ['biddably', 'biddable'],
        ['trace', 'traces', 'traced', 'tracing'],
        ['follow', 'follow', 'followed', 'following'],
      ],
    },
    {
      supplemental: 'of',
      first: null,
      second: null,
    },
    {
      top: 'life',
      first: [
        'life',
        'bud',
        'sprout',
        'alive',
        'lively',
        'new',
        'vigorously',
        'grow',
      ],
      second: [
        ['life', 'live', 'lives', 'lived', 'living'],
        ['bud', 'buds', 'budded', 'budding'],
        ['sprout', 'sprouts', 'sprouted', 'sprouting'],
        ['alive', 'aliveness'],
        ['lively', 'liveliness'],
        ['new', 'newly'],
        ['vigorously', 'vigor', 'vigorous'],
        ['grow', 'growth', 'grows', 'grew', 'growing'],
      ],
    },
    {
      top: 'alone',
      first: [
        'recluse',
        'loner',
        'unaided',
        'alone',
        'solely',
        'solitarily',
        'isolate',
        'withdraw',
      ],
      second: [
        ['recluse', 'recluses'],
        ['loner', 'loners'],
        ['alone', 'aloneness'],
        ['solitarily', 'solitary'],
        ['isolate', 'isolates', 'isolated', 'isolating'],
        ['withdraw', 'withdraws', 'withdrawing', 'withdrawn'],
      ],
    },
    {
      supplemental: '?',
      first: null,
      second: null,
    },
    {
      top: 'everyone',
      first: [
        'people',
        'everyone',
        'together',
        'thronged',
        'teemingly',
        'gather',
        'crowd',
      ],
      second: [
        ['people', 'peoples'],
        ['together', 'togetherness'],
        ['thronged', 'throng', 'throngs', 'thronging'],
        ['teemingly', 'teem', 'teems', 'teemed', 'teeming'],
        ['gather', 'gathers', 'gathered', 'gathering'],
        ['crowd', 'crowds', 'crowded', 'crowding'],
      ],
    },
    {
      supplemental: '…',
      first: null,
      second: null,
    },
    {
      top: 'no one',
      first: ['nobody', 'no one', 'desolate', 'vacantly', 'desert', 'abandon'],
      second: [
        ['desolate', 'desolately'],
        ['vacantly', 'vacant'],
        ['desert', 'deserts', 'deserted', 'deserting'],
        ['abandon', 'abandons', 'abandoned', 'abandoning'],
      ],
    },
    {
      supplemental: '.',
      first: null,
      second: null,
    },
  ];
  static SOLVED_1 = [
    {
      top: 'what',
      first: [
        'what',
        'everything',
        'box',
        'made',
        'wrought',
        'manifestly',
        'create',
        'forge',
      ],
      second: [
        ['everything', 'thing', 'things'],
        ['box', 'boxes'],
        ['made', 'make', 'makes', 'making'],
        ['create', 'creates', 'created', 'creating'],
        ['forge', 'forges', 'forged', 'forging'],
      ],
    },
    {
      top: 'could be',
      first: [
        'possiblility',
        'potential',
        'maybe',
        'perhaps',
        'might',
        'could be',
      ],
      second: [
        ['possiblility', 'possibilities', 'possible', 'possibly'],
        ['potential', 'potentially'],
        ['maybe', 'may', 'may have been'],
        ['might', 'might have'],
        ['could be', 'could have been'],
      ],
    },
    {
      top: 'better',
      first: [
        'plant',
        'benefit',
        'good',
        'better',
        'helpfully',
        'offer',
        'elevate',
      ],
      second: [
        ['plant', 'plants', 'planted', 'planting'],
        ['benefit', 'benefits', 'benefited', 'benefitting'],
        ['good', 'goodness'],
        ['better', 'best'],
        ['helpfully', 'help', 'helps', 'helped', 'helping', 'helpful'],
        ['offer', 'offers', 'offered', 'offering'],
        ['elevate', 'elevates', 'elevated', 'elevating'],
      ],
    },
    {
      supplemental: 'than',
      first: null,
      second: null,
    },
    {
      supplemental: 'to',
      first: null,
      second: null,
    },

    {
      top: 'sit',
      first: ['cushion', 'comforting', 'soothingly', 'sit'],
      second: [
        ['cushion', 'cushions', 'cushioned', 'cushioning'],
        ['comforting', 'comfort', 'comforts', 'comforted', 'comforting'],
        ['soothingly', 'soothe', 'soothes', 'soothed', 'soothing'],
        ['sit', 'sits', 'sat', 'sitting'],
      ],
    },
    {
      supplemental: 'in',
      first: null,
      second: null,
    },
    {
      supplemental: 'the',
      first: null,
      second: null,
    },
    {
      top: 'sun',
      first: [
        'sun',
        'daylight',
        'morning',
        'light',
        'early',
        'brightly',
        'dawn',
      ],
      second: [
        ['sun', 'suns', 'sunrise', 'sunrises'],
        ['morning', 'mornings'],
        ['light', 'lights', 'lighted', 'lighting'],
        [
          'brightly',
          'brightness',
          'bright',
          'brighten',
          'brightens',
          'brightened',
          'brightening',
        ],
        ['dawn', 'dawns', 'dawned', 'dawning'],
      ],
    },
    {
      supplemental: 'and',
      first: null,
      second: null,
    },
    {
      top: 'feel',
      first: ['vulnerability', 'receptive', 'openly', 'sense', 'feel'],
      second: [
        ['vulnerability', 'vulnerable'],
        [
          'receptive',
          'recieve',
          'recieves',
          'recieved',
          'recieving',
          'receptively',
        ],
        ['openly', 'openess', 'open'],
        ['sense', 'senses', 'sensed', 'sensing', 'sensual'],
        ['feel', 'feels', 'felt', 'feeling', 'feelings'],
      ],
    },
    {
      supplemental: 'the',
      first: null,
      second: null,
    },
    {
      top: 'soft',
      first: ['feather', 'velvety', 'soft', 'plush', 'gently', 'soften'],
      second: [
        ['feather', 'feathers', 'feathered', 'feathering', 'feathery'],
        ['velvety'],
        ['soft', 'softness', 'softly'],
        ['plush'],
        ['gently', 'gentle', 'gentles', 'gentled', 'gentling'],
        ['soften', 'softens', 'softened', 'softening'],
      ],
    },
    {
      top: 'wind',
      first: ['breeze', 'wind', 'sky', 'blustery', 'tempestuously', 'blow'],
      second: [
        ['breeze', 'breezes', 'breezy'],
        ['wind', 'winds', 'windy'],
        ['sky', 'skies'],
        ['blustery', 'bluster', 'blustered', 'blustering'],
        ['tempestuously', 'tempestuous'],
        ['blow', 'blows', 'blew', 'blowing'],
      ],
    },
    {
      supplemental: '?',
      first: null,
      second: null,
    },
  ];
  static SOLVED_2 = [
    {
      top: 'why',
      first: [
        'why',
        'bubble',
        'question',
        'mystery',
        'unknown',
        'quizzically',
        'wonder',
        'ask',
      ],
      second: [
        ['bubble', 'bubbles', 'bubbled', 'bubbling'],
        ['question', 'questions', 'questioned', 'questioning', 'questioningly'],
        ['mystery', 'mysteries', 'mysterious', 'mysteriously'],
        ['quizzically', 'quizzical'],
        ['wonder', 'wonders', 'wondered', 'wondering'],
        ['ask', 'asks', 'asked', 'asking'],
      ],
    },
    {
      supplemental: 'am',
      first: null,
      second: null,
    },
    {
      top: 'I',
      first: ['I', 'sight', 'eye', 'observant', 'look', 'see'],
      second: [
        ['I', 'me', 'myself', 'my', 'mine'],
        ['sight', 'sights'],
        ['eye', 'eyes', 'eyed', 'eyeing'],
        [
          'observant',
          'observe',
          'observes',
          'observed',
          'observing',
          'observantly',
        ],
        ['look', 'looks', 'looked', 'looking'],
        ['see', 'sees', 'saw', 'seeing'],
      ],
    },
    {
      top: 'afraid',
      first: [
        'expression',
        'fear',
        'nightmare',
        'afraid',
        'anxiously',
        'worry',
      ],
      second: [
        ['expression', 'expressions'],
        ['fear', 'fears', 'fearful', 'fearfully', 'feared', 'fearing'],
        ['nightmare', 'nightmares'],
        ['anxiously', 'anxiety', 'anxieties', 'anxious'],
        ['worry', 'worries', 'worried', 'worrying'],
      ],
    },
    {
      supplemental: 'to',
      first: null,
      second: null,
    },
    {
      top: 'live',
      first: [
        'bud',
        'sprout',
        'alive',
        'lively',
        'new',
        'vigorously',
        'grow',
        'live',
      ],
      second: [
        ['bud', 'buds', 'budded', 'budding'],
        ['sprout', 'sprouts', 'sprouted', 'sprouting'],
        ['alive', 'aliveness'],
        ['lively', 'liveliness'],
        ['new', 'newly'],
        ['vigorously', 'vigor', 'vigorous'],
        ['grow', 'growth', 'grows', 'grew', 'growing'],
        ['live', 'life', 'lives', 'lived', 'living'],
      ],
    },
    {
      supplemental: '?',
      first: null,
      second: null,
    },
    {
      top: 'because',
      first: [
        'because',
        'nut',
        'reason',
        'source',
        'first',
        'rooted',
        'fundamentally',
      ],
      second: [
        ['because', 'cause', 'causes', 'caused', 'causing'],
        ['nut', 'nuts'],
        ['reason', 'reasons'],
        ['source', 'sources'],
        ['first', 'firsts'],
        ['rooted', 'root', 'roots', 'rooting'],
        ['fundamentally', 'fundamental'],
      ],
    },
    {
      top: 'I',
      first: ['I', 'sight', 'eye', 'observant', 'look', 'see'],
      second: [
        ['I', 'me', 'myself', 'my', 'mine'],
        ['sight', 'sights'],
        ['eye', 'eyes', 'eyed', 'eyeing'],
        [
          'observant',
          'observe',
          'observes',
          'observed',
          'observing',
          'observantly',
        ],
        ['look', 'looks', 'looked', 'looking'],
        ['see', 'sees', 'saw', 'seeing'],
      ],
    },
    {
      supplemental: 'am',
      first: null,
      second: null,
    },
    {
      top: 'afraid',
      first: [
        'expression',
        'fear',
        'nightmare',
        'afraid',
        'anxiously',
        'worry',
      ],
      second: [
        ['expression', 'expressions'],
        ['fear', 'fears', 'fearful', 'fearfully', 'feared', 'fearing'],
        ['nightmare', 'nightmares'],
        ['anxiously', 'anxiety', 'anxieties', 'anxious'],
        ['worry', 'worries', 'worried', 'worrying'],
      ],
    },
    {
      supplemental: 'to',
      first: null,
      second: null,
    },
    {
      top: 'die',
      first: ['rest', 'bed', 'beir', 'dead', 'sleepily', 'die'],
      second: [
        ['rest', 'rests', 'rested', 'resting', 'restful', 'restfully'],
        ['bed', 'beds'],
        ['beir', 'beirs'],
        ['sleepily', 'sleep', 'sleeps', 'slept', 'sleeping', 'sleepy'],
        ['die', 'death', 'dies', 'died', 'dying'],
      ],
    },
    {
      supplemental: '.',
      first: null,
      second: null,
    },
  ];
  static SOLVED_3 = [
    {
      top: 'where',
      first: [
        'where',
        'planet',
        'globe',
        'world',
        'earthly',
        'ubiquitous',
        'everywhere',
        'always',
        'turn',
        'revolve',
      ],
      second: [
        ['planet', 'planets'],
        ['globe', 'globes'],
        ['world', 'worlds'],
        ['earthly', 'earth'],
        ['ubiquitous', 'ubiquity'],
        ['turn', 'turns', 'turned', 'turning'],
        [
          'revolve',
          'revolution',
          'revolutions',
          'revolves',
          'revolved',
          'revolving',
        ],
      ],
    },
    {
      top: 'they',
      first: [
        'they',
        'strangers',
        'their',
        'unaquainted',
        'unfamiliarly',
        'approach',
        'encounter',
      ],
      second: [
        ['they', 'them', 'themselves'],
        ['strangers', 'stranger'],
        ['their', 'theirs'],
        ['unfamiliarly', 'unfamiliar'],
        ['approach', 'approaches', 'approached', 'approaching'],
        ['encounter', 'encounters', 'encountered', 'encountering'],
      ],
    },
    {
      top: 'stood',
      first: [
        'you',
        'person',
        'your',
        'stalwart ',
        'steadfast',
        'faithfully',
        'prevail',
        'stood',
      ],
      second: [
        ['you', 'yourself'],
        ['person', 'persons', 'personal', 'personally'],
        ['your', 'yours'],
        ['stalwart ', 'stalwartly'],
        ['steadfast', 'steadfastly'],
        ['faithfully', 'faithful'],
        ['prevail', 'prevails', 'prevailed', 'prevailing', 'prevailingly'],
        ['stood', 'stance', 'stances', 'stand', 'stands', 'standing'],
      ],
    },
    {
      supplemental: ',',
      first: null,
      second: null,
    },

    {
      top: 'kissing',
      first: ['face', 'embrace', 'intimate', 'affectionately', 'kissing'],
      second: [
        ['face', 'faces', 'faced', 'facing'],
        ['embrace', 'embraces', 'embraced', 'embracing'],
        ['intimate', 'intimacy', 'intimacies', 'intimately'],
        ['affectionately', 'affection', 'affections', 'affectionate'],
        ['kissing', 'kiss', 'kisses', 'kissed'],
      ],
    },
    {
      supplemental: 'or',
      first: null,
      second: null,
    },
    {
      top: 'arguing',
      first: [
        'quarrel',
        'disagreement',
        'hostile',
        'truculent',
        'fractiously',
        'fight',
        'arguing',
      ],
      second: [
        ['quarrel', 'quarrels', 'quarrelled', 'quarrelling'],
        [
          'disagreement',
          'disagreements',
          'disagree',
          'disagrees',
          'disagreed',
          'disagreeing',
        ],
        ['hostile', 'hostility', 'hostilities'],
        ['truculent', 'truculence'],
        ['fractiously', 'fractious'],
        ['fight', 'fights', 'fought', 'fighting'],
        [
          'arguing',
          'argue',
          'argues',
          'argued',
          'arguementative',
          'arguementatively',
        ],
      ],
    },
    {
      supplemental: 'on',
      first: null,
      second: null,
    },
    {
      supplemental: 'the',
      first: null,
      second: null,
    },
    {
      top: 'shore',
      first: [
        'shore',
        'refuge',
        'verging',
        'skirting',
        'almost',
        'border',
        'harbor',
      ],
      second: [
        ['shore', 'shores'],
        ['refuge', 'refuges'],
        ['verging', 'verge', 'verges', 'verged'],
        ['skirting', 'skirt', 'skirts', 'skirted'],
        ['border', 'borders', 'bordered', 'bordering'],
        ['harbor', 'harbors', 'harbored', 'harboring'],
      ],
    },
    {
      supplemental: ',',
      first: null,
      second: null,
    },
    {
      top: 'sea',
      first: [
        'sea',
        'ocean',
        'wave',
        'undulating',
        'fluidly',
        'crest',
        'swell',
      ],
      second: [
        ['sea', 'seas'],
        ['ocean', 'oceans', 'oceanic'],
        ['wave', 'waves'],
        ['undulating', 'undulate', 'undulates', 'undulated'],
        ['fluidly', 'fluid'],
        ['crest', 'crests', 'crested', 'cresting'],
        ['swell', 'swells', 'swelled', 'swelling'],
      ],
    },
    {
      top: 'puddles',
      first: ['puddles', 'cumulative', 'collectively', 'accumulate', 'pool'],
      second: [
        ['puddles', 'puddle', 'puddled', 'puddling'],
        ['cumulative', 'cumulatively'],
        ['collectively', 'collective'],
        [
          'accumulate',
          'accumulation',
          'accumulates',
          'accumulated',
          'accumulating',
        ],
        ['pool', 'pools', 'pooled', 'pooling'],
      ],
    },
    {
      supplemental: '.',
      first: null,
      second: null,
    },
  ];
  static SOLVED_4 = [
    {
      top: 'when',
      first: [
        'when',
        'tomorrow',
        'future',
        'impending',
        'coming',
        'inevitably',
        'arrive',
      ],
      second: [
        ['tomorrow', 'tomorrows'],
        ['future', 'futures'],
        ['coming', 'come', 'comes', 'came'],
        ['inevitably', 'inevitability', 'inevitabilities', 'inevitable'],
        ['arrive', 'arrival', 'arrivals', 'arrives', 'arrived', 'arriving'],
      ],
    },
    {
      top: 'we',
      first: [
        'we',
        'family',
        'our',
        'kindred',
        'akin',
        'simillarly',
        'join',
        'group',
      ],
      second: [
        ['we', 'us', 'ourself', 'ourselves '],
        ['family', 'families', 'familiar'],
        ['our', 'ours'],
        ['simillarly', 'similar'],
        ['join', 'joins', 'joined', 'joining'],
        ['group', 'groups', 'grouped', 'grouping'],
      ],
    },
    {
      top: 'see',
      first: ['I', 'sight', 'eye', 'observant', 'look', 'see'],
      second: [
        ['I', 'me', 'myself', 'my', 'mine'],
        ['sight', 'sights'],
        ['eye', 'eyes', 'eyed', 'eyeing'],
        [
          'observant',
          'observe',
          'observes',
          'observed',
          'observing',
          'observantly',
        ],
        ['look', 'looks', 'looked', 'looking'],
        ['see', 'sees', 'saw', 'seeing'],
      ],
    },
    {
      top: 'each other',
      first: [
        'each other',
        'friend',
        'companionable',
        'gregarious',
        'amiably',
        'associate',
        'befriend',
      ],
      second: [
        ['friend', 'friends', 'friendly'],
        ['companionable', 'compainion', 'compainions'],
        ['gregarious', 'gregariously'],
        ['amiably', 'amiable'],
        ['associate', 'associates', 'associated', 'associating'],
        ['befriend', 'befriends', 'befriended', 'befriending'],
      ],
    },
    {
      top: 'clearly',
      first: ['petrichor', 'fresh', 'clearly', 'refresh', 'clarify'],
      second: [
        ['fresh', 'freshness', 'freshly'],
        ['clearly', 'clear', 'clears', 'cleared', 'clearing'],
        ['refresh', 'refreshes', 'refreshed', 'refreshing', 'refreshingly'],
        ['clarify', 'clarity', 'clarifies', 'clarified', 'clarifying'],
      ],
    },
    {
      supplemental: ',',
      first: null,
      second: null,
    },
    {
      top: 'our',
      first: [
        'we',
        'family',
        'our',
        'kindred',
        'akin',
        'simillarly',
        'join',
        'group',
      ],
      second: [
        ['we', 'us', 'ourself', 'ourselves'],
        ['family', 'families', 'familiar'],
        ['our', 'ours'],
        ['simillarly', 'similar'],
        ['join', 'joins', 'joined', 'joining'],
        ['group', 'groups', 'grouped', 'grouping'],
      ],
    },
    {
      top: 'hearts',
      first: ['heart', 'warm', 'cherished', 'lovingly', 'adore'],
      second: [
        ['heart', 'hearts'],
        ['warm', 'warmth', 'warms', 'warmed', 'warming'],
        ['cherished', 'cherish', 'cherishes', 'cherished', 'cherishing'],
        ['lovingly', 'love', 'loves', 'loved', 'loving'],
        ['adore', 'adores', 'adored', 'adoring', 'adoringly', 'adoration'],
      ],
    },
    {
      top: 'break',
      first: ['rift', 'crack ', 'torn', 'distructively', 'destroy', 'break'],
      second: [
        ['rift', 'rifts'],
        ['crack ', 'cracks', 'cracked', 'cracking'],
        ['torn', 'tear', 'tears', 'tearing'],
        ['distructively', 'distruction', 'distructive'],
        ['destroy', 'destroys', 'destroyed', 'destroying'],
        ['break', 'breaks', 'broke', 'breaking', 'broken'],
      ],
    },
    {
      supplemental: '.',
      first: null,
      second: null,
    },
  ];
  static SOLVED_5 = [
    {
      top: 'how',
      first: ['how', 'way', 'path', 'pliant', 'biddably', 'trace', 'follow'],
      second: [
        ['way', 'ways'],
        ['path', 'paths'],
        ['biddably', 'biddable'],
        ['trace', 'traces', 'traced', 'tracing'],
        ['follow', 'follow', 'followed', 'following'],
      ],
    },
    {
      top: 'everything',
      first: [
        'what',
        'everything',
        'box',
        'made',
        'wrought',
        'manifestly',
        'create',
        'forge',
      ],
      second: [
        ['everything', 'thing', 'things'],
        ['box', 'boxes'],
        ['made', 'make', 'makes', 'making'],
        ['create', 'creates', 'created', 'creating'],
        ['forge', 'forges', 'forged', 'forging'],
      ],
    },
    {
      top: 'ends',
      first: [
        'close',
        'ultimate',
        'lastly',
        'finally',
        'complete',
        'finish',
        'ends',
      ],
      second: [
        ['close', 'closes', 'closed', 'closing'],
        ['ultimate', 'ultimately'],
        ['lastly', 'last'],
        ['finally', 'final'],
        [
          'complete',
          'completion',
          'completes',
          'completed',
          'completing',
          'completely',
        ],
        ['finish', 'finishes', 'finished', 'finishing'],
        ['ends', 'endings', 'end', 'ended', 'ending'],
      ],
    },
    {
      top: 'we',
      first: [
        'we',
        'family',
        'our',
        'kindred',
        'akin',
        'simillarly',
        'join',
        'group',
      ],
      second: [
        ['we', 'us', 'ourself', 'ourselves'],
        ['family', 'families', 'familiar'],
        ['our', 'ours'],
        ['simillarly', 'similar'],
        ['join', 'joins', 'joined', 'joining'],
        ['group', 'groups', 'grouped', 'grouping'],
      ],
    },
    {
      top: 'know',
      first: [
        'lens',
        'clue',
        'true',
        'precisely',
        'discover',
        'learn',
        'find',
        'know',
      ],
      second: [
        ['lens', 'lenses'],
        ['clue', 'clues'],
        ['true', 'truth', 'truths', 'truly'],
        ['precisely', 'precise'],
        ['discover', 'discovery', 'discovers', 'discovered', 'discovering'],
        ['learn', 'learns', 'learned', 'learning'],
        ['find', 'finds', 'found', 'finding'],
        ['know', 'knowledge', 'knows', 'knowing', 'knowingly', 'known'],
      ],
    },
    {
      supplemental: '…',
      first: null,
      second: null,
    },
    {
      top: 'still',
      first: ['still', 'quiet', 'placid', 'tranquil', 'serenly', 'settle'],
      second: [
        ['still', 'stillness', 'stills', 'stilled', 'stilling'],
        ['quiet', 'quiets', 'quieted', 'quieting'],
        ['placid', 'placidly'],
        ['tranquil', 'tranquilly'],
        ['serenly', 'serene'],
        ['settle', 'settles', 'settled', 'settling'],
      ],
    },
    {
      top: 'we',
      first: [
        'we',
        'family',
        'our',
        'kindred',
        'akin',
        'simillarly',
        'join',
        'group',
      ],
      second: [
        ['we', 'us', 'ourself', 'ourselves'],
        ['family', 'families', 'familiar'],
        ['our', 'ours'],
        ['simillarly', 'similar'],
        ['join', 'joins', 'joined', 'joining'],
        ['group', 'groups', 'grouped', 'grouping'],
      ],
    },
    {
      top: 'begin',
      first: [
        'book',
        'start',
        'nascent',
        'incipient',
        'emergent',
        'initially',
        'begin',
      ],
      second: [
        ['book', 'books'],
        ['start', 'starts', 'started', 'starting'],
        ['emergent', 'emerge', 'emerges', 'emerged', 'emerging'],
        ['initially', 'initial'],
        ['begin', 'beginnings', 'begins', 'began', 'beginning'],
      ],
    },
    {
      supplemental: '.',
      first: null,
      second: null,
    },
  ];
  static SHUFFLED_0 = [
    {
      top: 'nobody',
      first: ['nobody', 'no one', 'desolate', 'vacantly', 'desert', 'abandon'],
      second: [
        ['desolate', 'desolately'],
        ['vacantly', 'vacant'],
        ['desert', 'deserts', 'deserted', 'deserting'],
        ['abandon', 'abandons', 'abandoned', 'abandoning'],
      ],
    },
    {
      top: 'rest',
      first: ['rest', 'bed', 'beir', 'dead', 'sleepily', 'die'],
      second: [
        ['rest', 'rests', 'rested', 'resting', 'restful', 'restfully'],
        ['bed', 'beds'],
        ['beir', 'beirs'],
        ['sleepily', 'sleep', 'sleeps', 'slept', 'sleeping', 'sleepy'],
        ['die', 'death', 'dies', 'died', 'dying'],
      ],
    },
    {
      top: 'amnesty',
      first: ['amnesty', 'pardon', 'forgiving', 'mercifully', 'absolve'],
      second: [
        ['pardon', 'pardons', 'pardoned', 'pardoning'],
        ['forgiving', 'forgiveness', 'forgive', 'forgives', 'forgave'],
        ['mercifully', 'mercy', 'merciful'],
        ['absolve', 'absolution', 'absolves', 'absolved', 'absolving'],
      ],
    },
    {
      top: 'exuberance',
      first: ['exuberance', 'irrepressible', 'eagerly', 'burst'],
      second: [
        ['exuberance', 'exuberant'],
        ['irrepressible', 'irrepressibly'],
        ['eagerly', 'eager', 'eagerness'],
        ['burst', 'bursts', 'bursted', 'bursting'],
      ],
    },
    {
      top: 'something',
      first: [
        'something',
        'variable',
        'indefinite',
        'unstated',
        'indeterminately',
        'guess',
      ],
      second: [
        ['variable', 'variables'],
        ['indefinite', 'indefinitely'],
        ['indeterminately', 'indeterminate'],
        ['guess', 'guesses', 'guessed', 'guessing'],
      ],
    },
    {
      top: 'each other',
      first: [
        'each other',
        'friend',
        'companionable',
        'gregarious',
        'amiably',
        'associate',
        'befriend',
      ],
      second: [
        ['friend', 'friends', 'friendly'],
        ['companionable', 'compainion', 'compainions'],
        ['gregarious', 'gregariously'],
        ['amiably', 'amiable'],
        ['associate', 'associates', 'associated', 'associating'],
        ['befriend', 'befriends', 'befriended', 'befriending'],
      ],
    },
    {
      top: 'sunset',
      first: [
        'sunset',
        'dusk',
        'twilight',
        'evening',
        'dark',
        'late',
        'dimly',
        'dwindle',
      ],
      second: [
        ['sunset', 'sunsets'],
        ['dusk', 'dusky'],
        ['twilight', 'twilit'],
        ['evening', 'evenings'],
        ['dark', 'darkness', 'darken', 'darkens', 'darkened', 'darkening'],
        ['dimly', 'dimness', 'dim', 'dims', 'dimmed', 'dimming'],
        ['dwindle', 'dwindles', 'dwindled', 'dwindling'],
      ],
    },
    {
      top: 'blind',
      first: ['blind', 'oblivious', 'unseeing', 'sightlessly', 'overlook'],
      second: [
        ['blind', 'blindness', 'blindly'],
        ['oblivious', 'obliviousness', 'obliviously'],
        ['sightlessly', 'sightless'],
        ['overlook', 'overlooks', 'overlooked', 'overlooking'],
      ],
    },
  ];
  static SHUFFLED_1 = [
    {
      top: 'heart',
      first: ['heart', 'warm', 'cherished', 'lovingly', 'adore'],
      second: [
        ['heart', 'hearts'],
        ['warm', 'warmth', 'warms', 'warmed', 'warming'],
        ['cherished', 'cherish', 'cherishes', 'cherished', 'cherishing'],
        ['lovingly', 'love', 'loves', 'loved', 'loving'],
        ['adore', 'adores', 'adored', 'adoring', 'adoringly', 'adoration'],
      ],
    },
    {
      top: 'step',
      first: [
        'step',
        'gait',
        'wanderer',
        'roaming',
        'meanderingly',
        'ramble',
        'walks',
      ],
      second: [
        ['step', 'steps', 'stepped', 'stepping'],
        ['wanderer', 'wanderers', 'wander', 'wanders', 'wandered', 'wandering'],
        ['roaming', 'roam', 'roams', 'roamed'],
        ['meanderingly', 'meander', 'meanders', 'meandered', 'meandering'],
        ['ramble', 'rambles', 'rambled', 'rambling'],
        ['walks', 'walk', 'walked', 'walking'],
      ],
    },
    {
      top: 'resistance',
      first: [
        'resistance',
        'dissent',
        'unwilling',
        'reluctant',
        'defiantly',
        'refuse',
      ],
      second: [
        ['resistance', 'resist', 'resists', 'resisted', 'resisting'],
        ['dissent', 'dissension', 'dissents', 'dissented', 'dissenting'],
        ['unwilling', 'unwillingly'],
        ['reluctant', 'reluctance', 'reluctantly'],
        ['defiantly', 'defiance', 'defiant'],
        ['refuse', 'refuses', 'refused', 'refusing'],
      ],
    },
    {
      top: 'something',
      first: [
        'something',
        'variable',
        'indefinite',
        'unstated',
        'indeterminately',
        'guess',
      ],
      second: [
        ['variable', 'variables'],
        ['indefinite', 'indefinitely'],
        ['indeterminately', 'indeterminate'],
        ['guess', 'guesses', 'guessed', 'guessing'],
      ],
    },
    {
      top: 'book',
      first: [
        'book',
        'start',
        'nascent',
        'incipient',
        'emergent',
        'initially',
        'begin',
      ],
      second: [
        ['book', 'books'],
        ['start', 'starts', 'started', 'starting'],
        ['emergent', 'emerge', 'emerges', 'emerged', 'emerging'],
        ['initially', 'initial'],
        ['begin', 'beginnings', 'begins', 'began', 'beginning'],
      ],
    },
    {
      top: 'unity',
      first: [
        'unity',
        'circle',
        'unified',
        'concordant',
        'harmoniously',
        'belong',
        'agree',
        'know',
      ],
      second: [
        ['unity', 'unite', 'unites', 'united', 'uniting'],
        ['circle', 'circles'],
        ['unified', 'unify', 'unifies', 'unifying'],
        ['concordant', 'concord', 'concords'],
        ['harmoniously', 'harmonious'],
        ['belong', 'belongs', 'belonged', 'belonging'],
        ['agree', 'agrees', 'agreed', 'agreeing'],
        ['know', 'knowledge', 'knows', 'knowing', 'knowingly', 'known'],
      ],
    },
    {
      top: 'fog',
      first: ['fog', 'nebulous', 'hazy', 'indistinctly', 'cloudy', 'blur'],
      second: [
        ['fog', 'fogs', 'fogged', 'fogging', 'foggy'],
        ['nebulous', 'nebulousness'],
        ['hazy', 'haze', 'hazily'],
        ['indistinctly', 'indistinct'],
        ['cloudy', 'clouds', 'clouded', 'clouding'],
        ['blur', 'blurs', 'blurred', 'blurring'],
      ],
    },
    {
      top: 'nobody',
      first: ['nobody', 'no one', 'desolate', 'vacantly', 'desert', 'abandon'],
      second: [
        ['desolate', 'desolately'],
        ['vacantly', 'vacant'],
        ['desert', 'deserts', 'deserted', 'deserting'],
        ['abandon', 'abandons', 'abandoned', 'abandoning'],
      ],
    },
  ];
  static SHUFFLED_2 = [
    {
      top: 'nobody',
      first: ['nobody', 'no one', 'desolate', 'vacantly', 'desert', 'abandon'],
      second: [
        ['desolate', 'desolately'],
        ['vacantly', 'vacant'],
        ['desert', 'deserts', 'deserted', 'deserting'],
        ['abandon', 'abandons', 'abandoned', 'abandoning'],
      ],
    },
    {
      top: 'blanket',
      first: ['blanket', 'muffled', 'muzzily', 'dampen'],
      second: [
        ['blanket', 'blankets', 'blanketed', 'blanketing'],
        ['muffled', 'muffle', 'muffles', 'muffled', 'muffling'],
        ['dampen', 'dampens', 'dampened', 'dampening'],
      ],
    },
    {
      top: 'flood',
      first: [
        'flood',
        'torrent',
        'overwhelming',
        'turbulently',
        'drown',
        'deluge',
      ],
      second: [
        ['flood', 'floods', 'flooded', 'flooding'],
        ['torrent', 'torrents'],
        ['overwhelming', 'overwhelm', 'overwhelms', 'overwhelmed'],
        ['turbulently', 'turbulent'],
        ['drown', 'drowns', 'drowned', 'drowning'],
        ['deluge', 'deluged'],
      ],
    },
    {
      top: 'petrichor',
      first: ['petrichor', 'fresh', 'clearly', 'refresh', 'clarify'],
      second: [
        ['fresh', 'freshness', 'freshly'],
        ['clearly', 'clear', 'clears', 'cleared', 'clearing'],
        ['refresh', 'refreshes', 'refreshed', 'refreshing', 'refreshingly'],
        ['clarify', 'clarity', 'clarifies', 'clarified', 'clarifying'],
      ],
    },
    {
      top: 'insight',
      first: ['insight', 'descerning', 'perceptively', 'recognize'],
      second: [
        ['insight', 'insights', 'insightful', 'insightfully'],
        ['descerning', 'descern', 'descerns', 'descerned'],
        [
          'perceptively',
          'perception',
          'perceptively',
          'perceive',
          'perceives',
          'perceived',
          'perceiving',
        ],
        ['recognize', 'recognizes', 'recognized', 'recognizing'],
      ],
    },
    {
      top: 'we',
      first: [
        'we',
        'family',
        'our',
        'kindred',
        'akin',
        'simillarly',
        'join',
        'group',
      ],
      second: [
        ['we', 'us', 'ourself', 'ourselves'],
        ['family', 'families', 'familiar'],
        ['our', 'ours'],
        ['simillarly', 'similar'],
        ['join', 'joins', 'joined', 'joining'],
        ['group', 'groups', 'grouped', 'grouping'],
      ],
    },
    {
      top: 'sun',
      first: [
        'sun',
        'daylight',
        'morning',
        'light',
        'early',
        'brightly',
        'dawn',
      ],
      second: [
        ['sun', 'suns', 'sunrise', 'sunrises'],
        ['morning', 'mornings'],
        ['light', 'lights', 'lighted', 'lighting'],
        [
          'brightly',
          'brightness',
          'bright',
          'brighten',
          'brightens',
          'brightened',
          'brightening',
        ],
        ['dawn', 'dawns', 'dawned', 'dawning'],
      ],
    },
    {
      top: 'doubt',
      first: [
        'doubt',
        'confusion',
        'dubious',
        'unsure',
        'uncertainly',
        'puzzle',
      ],
      second: [
        ['doubt', 'doubts', 'doubted', 'doubting', 'doubtful', 'doubtfully'],
        ['confusion', 'confuse', 'confuses', 'confused', 'confusing'],
        ['dubious', 'dubiously'],
        ['uncertainly', 'uncertainty', 'uncertain'],
        ['puzzle', 'puzzles', 'puzzled', 'puzzling'],
      ],
    },
  ];
  static SHUFFLED_3 = [
    {
      top: '',
      first: [
        'each other ',
        'friend',
        'companionable',
        'gregarious',
        'amiably',
        'associate',
        'befriend',
      ],
      second: [
        ['friend', 'friends', 'friendly'],
        ['companionable', 'compainion', 'companions'],
        ['gregarious', 'gregariously'],
        ['amiably', 'amiable'],
        ['associate', 'associates', 'associated', 'associating'],
        ['befriend', 'befriends', 'befriended', 'befriending'],
      ],
    },
    {
      top: 'petrichor',
      first: ['petrichor', 'fresh', 'clearly', 'refresh', 'clarify'],
      second: [
        ['fresh', 'freshness', 'freshly'],
        ['clearly', 'clear', 'clears', 'cleared', 'clearing'],
        ['refresh', 'refreshes', 'refreshed', 'refreshing', 'refreshingly'],
        ['clarify', 'clarity', 'clarifies', 'clarified', 'clarifying'],
      ],
    },
    {
      top: 'possiblility',
      first: [
        'possiblility',
        'potential',
        'maybe',
        'perhaps',
        'might',
        'could be',
      ],
      second: [
        ['possiblility', 'possibilities', 'possible', 'possibly'],
        ['potential', 'potentially'],
        ['maybe', 'may', 'may have been'],
        ['might', 'might have'],
        ['could be', 'could have been'],
      ],
    },
    {
      top: 'release',
      first: ['release', 'drop', 'free', 'loosely', 'surrender', 'let go'],
      second: [
        ['release', 'releases', 'released', 'releasing'],
        ['drop', 'drops', 'dropped', 'dropping'],
        ['free', 'frees', 'freed', 'freeing', 'freely'],
        ['loosely', 'loose', 'loosen', 'loosened', 'loosening'],
        ['surrender', 'surrenders', 'surrendered', 'surrendering'],
        ['let go', 'lets go', 'letting go'],
      ],
    },
    {
      top: 'hesitation',
      first: ['hesitation', 'reticent', 'shy', 'haltingly', 'wilt'],
      second: [
        [
          'hesitation',
          'hesitant',
          'hesitate',
          'hesitates',
          'hesitated',
          'hesitating',
          'hesitatingly',
        ],
        ['reticent', 'reticence', 'reticently'],
        ['shy', 'shyness', 'shyly'],
        ['haltingly', 'halting'],
        ['wilt', 'wilts', 'witled', 'wilting'],
      ],
    },
    {
      top: 'nobody',
      first: ['nobody', 'no one', 'desolate', 'vacantly', 'desert', 'abandon'],
      second: [
        ['desolate', 'desolately'],
        ['vacantly', 'vacant'],
        ['desert', 'deserts', 'deserted', 'deserting'],
        ['abandon', 'abandons', 'abandoned', 'abandoning'],
      ],
    },
    {
      top: 'hunt',
      first: ['hunt', 'curious', 'probingly', 'investigate', 'explore'],
      second: [
        ['hunt', 'hunts', 'hunted', 'hunting'],
        ['curious', 'curiosity', 'curiosites', 'curiously'],
        ['probingly', 'probe', 'probes', 'probed', 'probing'],
        [
          'investigate',
          'investigation',
          'investigations',
          'investigates',
          'investigated',
          'investigating',
        ],
        [
          'explore',
          'exploration',
          'explorations',
          'explores',
          'explored',
          'exploring',
        ],
      ],
    },
    {
      top: 'influx',
      first: [
        'influx',
        'mangrove',
        'replete',
        'awash',
        'abundantly',
        'engulf',
        'inundate',
      ],
      second: [
        ['influx', 'influxes'],
        ['mangrove', 'mangroves'],
        ['replete', 'repletely'],
        ['abundantly', 'abundance', 'abundant'],
        ['engulf', 'engulfs', 'engulfed', 'engulfing'],
        ['inundate', 'inundation', 'inundates', 'inundated', 'inundating'],
      ],
    },
  ];
  static SHUFFLED_4 = [
    {
      top: 'abyss',
      first: ['abyss', 'expanse', 'vast', 'nowhere', 'expand'],
      second: [
        ['abyss', 'abyssmal', 'abyssmally'],
        ['expanse', 'expansive'],
        ['vast', 'vastly'],
        ['expand', 'expands', 'expanded', 'expanding'],
      ],
    },
    {
      top: 'guide',
      first: ['guide', 'inspiring', 'persuasively', 'lead'],
      second: [
        ['guide', 'guides', 'guided', 'guiding'],
        ['inspiring', 'inspire', 'inspires', 'inspired', 'inspiring'],
        ['persuasively', 'persuasive'],
        ['lead', 'leads', 'led', 'leading'],
      ],
    },
    {
      top: 'shadow',
      first: [
        'shadow',
        'subconscious',
        'subliminal',
        'shrouded',
        'unconsciously',
        'repress',
      ],
      second: [
        ['shadow', 'shadows'],
        ['subconscious', 'subconsciously'],
        ['shrouded', 'shroud', 'shrouds', 'shrouding'],
        ['unconsciously', 'unconscious'],
        ['repress', 'represses', 'repressed', 'repressing'],
      ],
    },
    {
      top: 'they',
      first: [
        'they',
        'strangers',
        'their',
        'unaquainted',
        'unfamiliarly',
        'approach',
        'encounter',
      ],
      second: [
        ['they', 'them', 'themselves'],
        ['strangers', 'stranger'],
        ['their', 'theirs'],
        ['unfamiliarly', 'unfamiliar'],
        ['approach', 'approaches', 'approached', 'approaching'],
        ['encounter', 'encounters', 'encountered', 'encountering'],
      ],
    },
    {
      top: 'he',
      first: ['he', 'man', 'his', 'volant', 'aloft', 'soaringly', 'fly'],
      second: [
        ['he', 'him', 'himself'],
        ['man', 'men'],
        ['soaringly', 'soar', 'soars', 'soared', 'soaring'],
        ['fly', 'flight', 'flies', 'flew', 'flying'],
      ],
    },
    {
      top: 'they',
      first: [
        'they',
        'strangers',
        'their',
        'unaquainted',
        'unfamiliarly',
        'approach',
        'encounter',
      ],
      second: [
        ['they', 'them', 'themselves'],
        ['strangers', 'stranger'],
        ['their', 'theirs'],
        ['unfamiliarly', 'unfamiliar'],
        ['approach', 'approaches', 'approached', 'approaching'],
        ['encounter', 'encounters', 'encountered', 'encountering'],
      ],
    },
    {
      top: 'feather',
      first: ['feather', 'velvety', 'soft', 'plush', 'gently', 'soften'],
      second: [
        ['feather', 'feathers', 'feathered', 'feathering', 'feathery'],
        ['soft', 'softness', 'softly'],
        ['gently', 'gentle', 'gentles', 'gentled', 'gentling'],
        ['soften', 'softens', 'softened', 'softening'],
      ],
    },
    {
      top: 'aftershock',
      first: [
        'aftershock',
        'reprecussion',
        'ensuing',
        'consequently',
        'resoundingly',
        'echo',
        'reverberate',
      ],
      second: [
        ['aftershock', 'aftershocks'],
        ['reprecussion', 'reprecussions'],
        ['ensuing', 'ensue', 'ensues', 'ensued'],
        ['consequently', 'consequence', 'consequences'],
        ['resoundingly', 'resounding'],
        ['echo', 'echoes', 'echoed', 'echoing'],
        [
          'reverberate',
          'reverberation',
          'reverberations',
          'reverberates',
          'reverberated',
          'reverberating',
        ],
      ],
    },
  ];
  static SHUFFLED_5 = [
    {
      top: 'from',
      first: [
        'from',
        'ancestor',
        'heritage',
        'wellspring',
        'influential',
        'emanate',
      ],
      second: [
        ['ancestor', 'ancestors'],
        ['influential', 'influence', 'influences', 'influenced', 'influencing'],
        ['emanate', 'emanates', 'emanated', 'emanating'],
      ],
    },
    {
      top: 'foresight',
      first: [
        'foresight',
        'premonition',
        'visionary',
        'presciently',
        'envision',
        'foresee',
        'dream',
      ],
      second: [
        ['premonition', 'premonitions'],
        ['visionary', 'vision', 'visions'],
        ['presciently', 'prescience', 'prescient'],
        ['envision', 'envisions', 'envisioned', 'envisioning'],
        ['foresee', 'foresees', 'forsaw', 'forseeing'],
        ['dream', 'dreams', 'dreamt', 'dreaming'],
      ],
    },
    {
      top: 'flood',
      first: [
        'flood',
        'torrent',
        'overwhelming',
        'turbulently',
        'drown',
        'deluge',
      ],
      second: [
        ['flood', 'floods', 'flooded', 'flooding'],
        ['torrent', 'torrents'],
        ['overwhelming', 'overwhelm', 'overwhelms', 'overwhelmed'],
        ['turbulently', 'turbulent'],
        ['drown', 'drowns', 'drowned', 'drowning'],
        ['deluge', 'deluged'],
      ],
    },
    {
      top: 'close',
      first: [
        'close',
        'ultimate',
        'lastly',
        'finally',
        'complete',
        'finish',
        'ends',
      ],
      second: [
        ['close', 'closes', 'closed', 'closing'],
        ['ultimate', 'ultimately'],
        ['lastly', 'last'],
        ['finally', 'final'],
        [
          'complete',
          'completion',
          'completes',
          'completed',
          'completing',
          'completely',
        ],
        ['finish', 'finishes', 'finished', 'finishing'],
        ['ends', 'endings', 'end', 'ended', 'ending'],
      ],
    },
    {
      top: 'courage',
      first: [
        'courage',
        'resolve',
        'brave',
        'undaunted',
        'fearlessly',
        'embolden',
        'hearten',
      ],
      second: [
        ['courage', 'courageous', 'courageously'],
        ['resolve', 'resolute'],
        ['brave', 'bravery', 'bravely'],
        ['fearlessly', 'fearlessness', 'fearless'],
        ['embolden', 'emboldens', 'emboldened', 'emboldening'],
        ['hearten', 'heartens', 'heartened', 'heartening'],
      ],
    },
    {
      top: 'ooze',
      first: ['ooze', 'leaky', 'slowly', 'trickle', 'seep'],
      second: [
        ['ooze', 'oozes', 'oozed', 'oozing'],
        ['leaky', 'leak', 'leaks', 'leaked', 'leaking'],
        ['slowly', 'slow', 'slows', 'slowed', 'slowing'],
        ['trickle', 'trickles', 'trickled', 'trickling'],
        ['seep', 'seepage', 'seepages', 'seeps', 'seeped', 'seeping'],
      ],
    },
    {
      top: 'how',
      first: ['how', 'way', 'path', 'pliant', 'biddably', 'trace', 'follow'],
      second: [
        ['way', 'ways'],
        ['path', 'paths'],
        ['biddably', 'biddable'],
        ['trace', 'traces', 'traced', 'tracing'],
        ['follow', 'follow', 'followed', 'following'],
      ],
    },
    {
      top: 'each other',
      first: [
        'each other',
        'friend',
        'companionable',
        'gregarious',
        'amiably',
        'associate',
        'befriend',
      ],
      second: [
        ['friend', 'friends', 'friendly'],
        ['companionable', 'companion', 'companions'],
        ['gregarious', 'gregariously'],
        ['amiably', 'amiable'],
        ['associate', 'associates', 'associated', 'associating'],
        ['befriend', 'befriends', 'befriended', 'befriending'],
      ],
    },
  ];
}

export { WordLists_Solved, Supplemental };
